PATH = '/Users/donald/Google Drive/Basketball Model/Basketball-Model/'
YAMP = '/Users/donald/Google Drive/Basketball Model/yaml_files/'
SITE = 'http://www.basketball-reference.com/'
CSTR = '<h2 data-mobile-header="" style="">'
BOXT = '<h2 data-mobile-header="" style="'
SRVR = 'Donalds-Mini.hsd1.in.comcast.net'
USER = 'ruby'
PSWD = 'Rubycon1$'
SCMA = 'bball'