USE BBALL;
DROP TABLE IF EXISTS NBA_GAME_LIST;

CREATE TABLE IF NOT EXISTS NBA_GAME_LIST (
BOX_SCORE_TEXT VARCHAR(12) PRIMARY KEY,
BS_COMPLETE INT,
PBP_COMPLETE INT,
PM_COMPLETE INT);

INSERT INTO NBA_GAME_LIST (BOX_SCORE_TEXT)
SELECT DISTINCT BOX_SCORE_TEXT
FROM NBA_REGULAR_SEASON A
WHERE A.BOX_SCORE_TEXT != ' '
;

INSERT INTO NBA_GAME_LIST (BOX_SCORE_TEXT)
SELECT DISTINCT BOX_SCORE_TEXT
FROM NBA_PLAYOFFS A
WHERE A.BOX_SCORE_TEXT != ' '
;