USE BBALL;
UPDATE NBA_ROSTER A
SET A.HEIGHT = (
	SELECT B.HEIGHT
    FROM NBA_HEIGHT_FIX B
    WHERE A.TEAM = B.TEAM
		AND A.YEAR = B.YEAR
        AND A.NUMBER = B.NUMBER
        AND A.PLAYER = B.PLAYER
        )
WHERE EXISTS (
	SELECT B.HEIGHT
    FROM NBA_HEIGHT_FIX B
    WHERE A.TEAM = B.TEAM
		AND A.YEAR = B.YEAR
        AND A.NUMBER = B.NUMBER
        AND A.PLAYER = B.PLAYER
        )
;